import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/login');
  await page.getByRole('textbox', { name: 'Usuario' }).click();
  await page.getByRole('textbox', { name: 'Usuario' }).fill('prueba1');
  await page.locator('div:nth-child(4) > .input-box').click();
  await page.getByRole('textbox', { name: '********' }).fill('admin1');
  await page.getByRole('button', { name: 'Iniciar Sesión' }).click();
  await page.getByRole('button', { name: 'Nuevo Beneficiario' }).click();
  await page.locator('input[name="email"]').click();
  await page.locator('input[name="email"]').click();
  await page.locator('input[name="email"]').click();
  await page.locator('input[name="email"]').fill('prueba@test.com');
  await page.locator('input[name="telefono"]').click();
  await page.locator('input[name="telefono"]').fill('1233405496');
  await page.locator('input[name="nombres"]').click();
  await page.locator('input[name="nombres"]').fill('Javier');
  await page.locator('input[name="apellido_paterno"]').click();
  await page.locator('input[name="apellido_paterno"]').fill('Plutarc');
  await page.locator('input[name="apellido_paterno"]').click();
  await page.locator('input[name="apellido_materno"]').click();
  await page.locator('input[name="apellido_materno"]').fill('Limas');
  await page.locator('input[name="fecha_nacimiento"]').fill('2026-04-28');
  await page.getByRole('textbox', { name: 'XXXX000000XXXXXX00' }).click();
  await page.locator('section').filter({ hasText: 'Datos PersonalesInformación M' }).locator('section').click();
  await page.getByRole('textbox', { name: 'XXXX000000XXXXXX00' }).click();
  await page.getByRole('textbox', { name: 'XXXX000000XXXXXX00' }).press('ControlOrMeta+v');
  await page.getByRole('textbox', { name: 'XXXX000000XXXXXX00' }).fill('PELJ000101HNLXX');
  await page.getByText('GéneroSeleccionar género...').click();
  await page.locator('select[name="genero"]').selectOption('masculino');
  await page.getByRole('textbox', { name: 'XXXX000000XXXXXX00' }).dblclick();
  await page.getByRole('textbox', { name: 'XXXX000000XXXXXX00' }).press('ControlOrMeta+v');
  await page.getByRole('textbox', { name: 'XXXX000000XXXXXX00' }).fill('JULI000101HNLXXYTK');
  await page.locator('select[name="estado_nacimiento"]').selectOption('Nuevo Leon');
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.locator('input[name="contacto_nombre"]').click();
  await page.locator('input[name="contacto_nombre"]').fill('fmfmdrfgmfdm');
  await page.locator('input[name="contacto_telefono"]').click();
  await page.locator('input[name="contacto_telefono"]').fill('3049545034');
  await page.locator('input[name="contacto_parentesco"]').click();
  await page.locator('input[name="contacto_parentesco"]').fill('mdfdfmmdfm');
  await page.locator('select[name="tipo_sanguineo"]').selectOption('B-');
  await page.locator('label').filter({ hasText: 'Espina Bífida Oculta' }).click();
  await page.getByText('Lipocele').click();
  await page.locator('input[name="padre_nombre"]').click();
  await page.locator('input[name="padre_nombre"]').fill('dmfmgfm');
  await page.locator('input[name="padre_email"]').click();
  await page.locator('input[name="contacto_nombre"]').dblclick();
  await page.locator('input[name="contacto_nombre"]').dblclick();
  await page.locator('input[name="contacto_nombre"]').fill('Maria');
  await page.locator('input[name="contacto_parentesco"]').click();
  await page.locator('input[name="contacto_parentesco"]').fill('mdfdfmmdfmMa');
  await page.locator('input[name="contacto_parentesco"]').dblclick();
  await page.locator('input[name="contacto_parentesco"]').fill('Madre');
  await page.locator('input[name="hospital"]').click();
  await page.locator('input[name="hospital"]').fill('Angeles');
  await page.locator('input[name="padre_nombre"]').click();
  await page.locator('input[name="padre_nombre"]').fill('');
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.locator('input[name="domicilio_calle"]').click();
  await page.locator('input[name="domicilio_calle"]').fill('Siempre Viva');
  await page.getByRole('combobox').selectOption('Michoacan');
  await page.locator('input[name="domicilio_ciudad"]').click();
  await page.locator('input[name="domicilio_ciudad"]').fill('');
  await page.getByRole('combobox').selectOption('Nuevo Leon');
  await page.locator('input[name="domicilio_ciudad"]').click();
  await page.locator('input[name="domicilio_ciudad"]').fill('Monterrey');
  await page.locator('input[name="domicilio_cp"]').click();
  await page.locator('input[name="domicilio_cp"]').fill('64000');
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByRole('button', { name: 'Registrar' }).click();
  await page.getByText('Ya existe un registro con datos unicos de beneficiario.');
});