export const SELECT_SALDO_AGREGADO = `
  SELECT
    NVL(SUM(fd.SALDO), 0) AS SALDO,
    TO_CHAR(MAX(fd.FECHA_ACTUALIZACION), 'YYYY-MM-DD HH24:MI') AS FECHA_ACTUALIZACION
  FROM FONDO_DONADOR fd
`;

export const SELECT_DONADORES_CON_FONDO = `
  SELECT
    d.ID_DONADOR,
    d.TIPO_ORIGEN,
    d.NOMBRE,
    fd.ID_FONDO,
    fd.SALDO,
    TO_CHAR(fd.FECHA_ACTUALIZACION, 'YYYY-MM-DD HH24:MI') AS FECHA_ACTUALIZACION
  FROM DONADORES d
  INNER JOIN FONDO_DONADOR fd ON fd.ID_DONADOR = d.ID_DONADOR
  ORDER BY d.NOMBRE
`;

export const SELECT_DONADOR_POR_TIPO_NOMBRE = `
  SELECT ID_DONADOR
  FROM DONADORES
  WHERE TIPO_ORIGEN = :tipo_origen
    AND UPPER(TRIM(NOMBRE)) = UPPER(TRIM(:nombre))
    AND ROWNUM = 1
`;

export const SELECT_NEXT_ID_DONADOR = `
  SELECT NVL(MAX(ID_DONADOR), 0) + 1 AS NEXT_ID FROM DONADORES
`;

export const SELECT_NEXT_ID_FONDO = `
  SELECT NVL(MAX(ID_FONDO), 0) + 1 AS NEXT_ID FROM FONDO_DONADOR
`;

export const INSERT_DONADOR = `
  INSERT INTO DONADORES (ID_DONADOR, TIPO_ORIGEN, NOMBRE, FECHA_ALTA)
  VALUES (:id_donador, :tipo_origen, :nombre, SYSDATE)
`;

export const INSERT_FONDO_DONADOR = `
  INSERT INTO FONDO_DONADOR (ID_FONDO, ID_DONADOR, SALDO, FECHA_ACTUALIZACION)
  VALUES (:id_fondo, :id_donador, 0, SYSDATE)
`;

export const SELECT_DONADOR_FONDO = `
  SELECT
    d.ID_DONADOR,
    fd.ID_FONDO,
    d.TIPO_ORIGEN,
    d.NOMBRE,
    fd.SALDO,
    TO_CHAR(fd.FECHA_ACTUALIZACION, 'YYYY-MM-DD HH24:MI') AS FECHA_ACTUALIZACION
  FROM DONADORES d
  INNER JOIN FONDO_DONADOR fd ON fd.ID_DONADOR = d.ID_DONADOR
  WHERE d.ID_DONADOR = :id_donador
`;

export const SELECT_FONDO_DONADOR_FOR_UPDATE = `
  SELECT
    fd.ID_FONDO,
    fd.ID_DONADOR,
    fd.SALDO,
    d.TIPO_ORIGEN,
    d.NOMBRE
  FROM FONDO_DONADOR fd
  INNER JOIN DONADORES d ON d.ID_DONADOR = fd.ID_DONADOR
  WHERE fd.ID_FONDO = :id_fondo
  FOR UPDATE OF fd.SALDO
`;

export const UPDATE_FONDO_DONADOR_SALDO = `
  UPDATE FONDO_DONADOR
  SET SALDO = :saldo,
      FECHA_ACTUALIZACION = SYSDATE
  WHERE ID_FONDO = :id_fondo
`;

export const INSERT_MOVIMIENTO_FONDO = `
  INSERT INTO MOVIMIENTOS_FONDO_DONACIONES (
    TIPO_MOVIMIENTO,
    MONTO,
    SALDO_ANTERIOR,
    SALDO_NUEVO,
    ORIGEN_TIPO,
    ORIGEN_NOMBRE,
    CONCEPTO,
    ID_SERVICIO_OTORGADO,
    ID_USUARIO,
    MOTIVO,
    ID_DONADOR,
    ID_FONDO
  ) VALUES (
    :tipo_movimiento,
    :monto,
    :saldo_anterior,
    :saldo_nuevo,
    :origen_tipo,
    :origen_nombre,
    :concepto,
    :id_servicio_otorgado,
    :id_usuario,
    :motivo,
    :id_donador,
    :id_fondo
  )
  RETURNING ID_MOVIMIENTO INTO :id_movimiento
`;

export const SELECT_MOVIMIENTOS_FONDO = `
  SELECT *
  FROM (
    SELECT
      m.ID_MOVIMIENTO,
      m.TIPO_MOVIMIENTO,
      m.MONTO,
      m.SALDO_ANTERIOR,
      m.SALDO_NUEVO,
      m.ORIGEN_TIPO,
      m.ORIGEN_NOMBRE,
      m.CONCEPTO,
      m.ID_SERVICIO_OTORGADO,
      m.ID_SERVICIO_OTORGADO AS FOLIO_SERVICIO,
      m.ID_DONADOR,
      m.ID_FONDO,
      d.NOMBRE AS DONADOR_NOMBRE,
      d.TIPO_ORIGEN AS DONADOR_TIPO,
      cs.NOMBRE AS NOMBRE_SERVICIO,
      m.ID_USUARIO,
      TO_CHAR(m.FECHA, 'YYYY-MM-DD HH24:MI') AS FECHA,
      m.MOTIVO
    FROM MOVIMIENTOS_FONDO_DONACIONES m
    LEFT JOIN DONADORES d ON d.ID_DONADOR = m.ID_DONADOR
    LEFT JOIN SERVICIOS_OTORGADOS so
      ON so.ID_SERVICIO_OTORGADO = m.ID_SERVICIO_OTORGADO
    LEFT JOIN CATALOGO_SERVICIOS cs
      ON cs.ID_CATALOGO_SERVICIO = so.ID_CATALOGO_SERVICIO
    ORDER BY m.FECHA DESC, m.ID_MOVIMIENTO DESC
  )
  WHERE ROWNUM <= :limite
`;

export const SELECT_MOVIMIENTOS_FONDO_POR_DONADOR = `
  SELECT *
  FROM (
    SELECT
      m.ID_MOVIMIENTO,
      m.TIPO_MOVIMIENTO,
      m.MONTO,
      m.SALDO_ANTERIOR,
      m.SALDO_NUEVO,
      m.ORIGEN_TIPO,
      m.ORIGEN_NOMBRE,
      m.CONCEPTO,
      m.ID_SERVICIO_OTORGADO,
      m.ID_SERVICIO_OTORGADO AS FOLIO_SERVICIO,
      m.ID_DONADOR,
      m.ID_FONDO,
      d.NOMBRE AS DONADOR_NOMBRE,
      d.TIPO_ORIGEN AS DONADOR_TIPO,
      cs.NOMBRE AS NOMBRE_SERVICIO,
      m.ID_USUARIO,
      TO_CHAR(m.FECHA, 'YYYY-MM-DD HH24:MI') AS FECHA,
      m.MOTIVO
    FROM MOVIMIENTOS_FONDO_DONACIONES m
    LEFT JOIN DONADORES d ON d.ID_DONADOR = m.ID_DONADOR
    LEFT JOIN SERVICIOS_OTORGADOS so
      ON so.ID_SERVICIO_OTORGADO = m.ID_SERVICIO_OTORGADO
    LEFT JOIN CATALOGO_SERVICIOS cs
      ON cs.ID_CATALOGO_SERVICIO = so.ID_CATALOGO_SERVICIO
    WHERE m.ID_DONADOR = :id_donador
    ORDER BY m.FECHA DESC, m.ID_MOVIMIENTO DESC
  )
  WHERE ROWNUM <= :limite
`;

export const SELECT_MONTO_DONACION_POR_SERVICIO = `
  SELECT NVL(MONTO, 0) AS MONTO
  FROM MOVIMIENTOS_FONDO_DONACIONES
  WHERE ID_SERVICIO_OTORGADO = :id_servicio_otorgado
    AND TIPO_MOVIMIENTO = 'egreso'
    AND ROWNUM = 1
`;
