export const SELECT_TIPOS_SERVICIO = `
    SELECT id_catalogo_servicio, nombre, categoria, precio
    FROM catalogo_servicios
    ORDER BY categoria, nombre
`;

export const INSERT_SERVICIO_OTORGADO = `
  INSERT INTO SERVICIOS_OTORGADOS 
    (ID_BENEFICIARIO, ID_CATALOGO_SERVICIO, FECHA, HORA, ID_CITA, CANTIDAD, NOTAS)
  VALUES 
    (:id_beneficiario, :id_catalogo_servicio, TO_DATE(:fecha, 'YYYY-MM-DD'), :hora, :id_cita, :cantidad, :notas)
  RETURNING ID_SERVICIO_OTORGADO INTO :id_servicio_otorgado
`;

export const INSERT_VENTA_INVENTARIO = `
  INSERT INTO VENTA_INVENTARIO 
    (ID_SERVICIO_OTORGADO, ID_INVENTARIO, CANTIDAD, PRECIO_UNITARIO, SUBTOTAL)
  VALUES 
    (:id_servicio_otorgado, :id_inventario, :cantidad, :precio_unitario, :subtotal)
`;

export const INSERT_SERVICIO_FINANCIERO = `
  INSERT INTO SERVICIOS_FINANCIEROS 
    (ID_SERVICIO_OTORGADO, MONTO_SERVICIO, MONTO_INVENTARIO, DESCUENTO, CUOTA_TOTAL, MONTO_PAGADO, MONTO_DONACION, METODO_PAGO, YA_APORTO)
  VALUES 
    (:id_servicio_otorgado, :monto_servicio, :monto_inventario, :descuento, :cuota_total, :monto_pagado, :monto_donacion, :metodo_pago, :ya_aporto)
`;

export const SELECT_CANTIDAD_INVENTARIO = `
  SELECT CANTIDAD
  FROM INVENTARIO
  WHERE ID_INVENTARIO = :id_inventario
`;

export const UPDATE_CANTIDAD_INVENTARIO = `
  UPDATE INVENTARIO
  SET CANTIDAD = CANTIDAD - :cantidad
  WHERE ID_INVENTARIO = :id_inventario
`;

export const INSERT_MOVIMIENTO_INVENTARIO = `
  INSERT INTO MOVIMIENTOS_INVENTARIO
    (ID_INVENTARIO, TIPO_MOVIMIENTO, CANTIDAD, FECHA, CANT_ANTERIOR, CANT_NUEVA, ID_SERVICIO_OTORGADO, ID_USUARIO, MOTIVO)
  VALUES
    (:id_inventario, 'salida', :cantidad, SYSDATE, :cant_anterior, :cant_nueva, :id_servicio_otorgado, :id_usuario, 'Venta Cliente')
`;

export const SELECT_FECHAS_ULTIMOS_ESTUDIOS_BY_BENEFICIARIO = `
  SELECT
    so.ID_BENEFICIARIO,

    MAX(CASE 
      WHEN UPPER(TRIM(cs.NOMBRE)) = 'ESTUDIOS ESPECIALIZADOS' 
      THEN so.FECHA 
    END) AS GRAL_ORINA,

    MAX(CASE 
      WHEN UPPER(TRIM(cs.NOMBRE)) = 'ECO VIAS URINARIAS' 
      THEN so.FECHA 
    END) AS ECO_RENAL,

    MAX(CASE 
      WHEN UPPER(TRIM(cs.NOMBRE)) LIKE 'UROTAC%' 
      THEN so.FECHA 
    END) AS UROTAC,

    MAX(CASE 
      WHEN UPPER(TRIM(cs.NOMBRE)) LIKE 'GAMMAGRAMA RENAL%' 
      THEN so.FECHA 
    END) AS EST_URODINAMICO,

    MAX(CASE 
      WHEN UPPER(TRIM(cs.NOMBRE)) LIKE 'TAC%' 
      THEN so.FECHA 
    END) AS TAC_CEREBRO,

    MAX(CASE 
      WHEN UPPER(TRIM(cs.NOMBRE)) LIKE '%UROCULTIVO%' 
      THEN so.FECHA 
    END) AS UROCULTIVO

  FROM SERVICIOS_OTORGADOS so
  JOIN CATALOGO_SERVICIOS cs
    ON so.ID_CATALOGO_SERVICIO = cs.ID_CATALOGO_SERVICIO
  WHERE UPPER(TRIM(cs.CATEGORIA)) = 'ESTUDIOS'
    AND so.ID_BENEFICIARIO = :id_beneficiario
  GROUP BY so.ID_BENEFICIARIO
`;

export const SELECT_HISTORIAL_SERVICIOS = `
  SELECT
    so.ID_SERVICIO_OTORGADO,
    i.NOMBRES || ' ' || i.APELLIDO_PATERNO || ' ' || NVL(i.APELLIDO_MATERNO, '') AS BENEFICIARIO,
    cs.NOMBRE        AS SERVICIO,
    cs.CATEGORIA,
    TO_CHAR(so.FECHA, 'YYYY-MM-DD')  AS FECHA,
    so.HORA,
    sf.MONTO_SERVICIO,
    sf.MONTO_INVENTARIO,
    sf.DESCUENTO,
    sf.CUOTA_TOTAL,
    sf.MONTO_PAGADO,
    sf.METODO_PAGO,
    sf.YA_APORTO,
    sf.MONTO_DONACION
  FROM SERVICIOS_OTORGADOS so
  JOIN CATALOGO_SERVICIOS     cs ON so.ID_CATALOGO_SERVICIO = cs.ID_CATALOGO_SERVICIO
  JOIN EQUIPO.BENEFICIARIO    b  ON so.ID_BENEFICIARIO      = b.ID_BENEFICIARIO
  JOIN EQUIPO.IDENTIFICADORES i  ON b.ID_BENEFICIARIO       = i.ID_BENEFICIARIO
  LEFT JOIN SERVICIOS_FINANCIEROS sf ON so.ID_SERVICIO_OTORGADO = sf.ID_SERVICIO_OTORGADO
  ORDER BY so.ID_SERVICIO_OTORGADO DESC
  OFFSET :offset ROWS FETCH NEXT :limit ROWS ONLY
`;
 
export const SELECT_CATEGORIAS_CATALOGO = `
  SELECT DISTINCT CATEGORIA
  FROM CATALOGO_SERVICIOS
  ORDER BY CATEGORIA
`;
 
export const INSERT_CATALOGO_SERVICIO = `
  INSERT INTO CATALOGO_SERVICIOS (NOMBRE, CATEGORIA, PRECIO)
  VALUES (:nombre, :categoria, :precio)
  RETURNING ID_CATALOGO_SERVICIO INTO :id_catalogo_servicio
`;
